name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-bot:
    runs-on: ubuntu-latest

    steps:
        - name: Send Telegram message on push (Success)
          if: success()
          uses: appleboy/telegram-action@master
          with:
            to: -4587543996
            token: 7807568169:AAFEHwd6wujmyeC4j8VBQl-61H-HjxU4-z8
            message: "Сообщение (строка #2)"

        - name: Send Telegram message on push (Failure)
          if: failure()
          uses: appleboy/telegram-action@master
          with:
            to: -4587543996
            token: 7807568169:AAFEHwd6wujmyeC4j8VBQl-61H-HjxU4-z8
            message: "Сообщение (строка #1)"